name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1']
        gemfile: ['52', '61', '70']
        exclude:
        - {ruby: '3.0', gemfile: '52'}
        - {ruby: '3.0', gemfile: '61'}
        - {ruby: '3.1', gemfile: '52'}
        - {ruby: '3.1', gemfile: '61'}
    name: ruby${{ matrix.ruby }} gemfiles/${{ matrix.gemfile }}.gemfile rake
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_DEPLOYMENT: "false"
    steps:
    - uses: zendesk/checkout@v2
    - uses: zendesk/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rake
